#write a pyhton prpgram to prints union.
a={1,2,3,4}
b={2,3,5,6}
print(a.union(b))
print(a|b)
#intersection():
a={1,2,3,4}
b={2,3,5,6}
print(a.intersection(b))
print(a&b)
#intersection_update():
a={1,2,3,4}
b={2,3,5,6}
a.intersection_update(b)
print(a)
#diffrence():
a={1,2,3,4}
b={2,3,5,6}
print(a.difference(b))
print(a-b)
#difference_update():
b={2,3,5,6}
a.difference_update(b)
print(a)
#symmetric_difference():
a={1,2,3,4}
b={2,3,5,6}
print(a.symmetric_difference(b))
print(a^b)
#symmetric_difference_update():
a={1,2,3,4}
b={2,3,5,6}
a.symmetric_difference_update(b)
print(a)
#isdisjoint():
a={1,2,3,4}
b={2,3,5,6}
print(a.isdisjoint(b))
#issubset():
a={1,2,3,4}
b={2,3}
print(a.issuperset(b))
#issuperset():
a={1,2,3,4}
b={2,3}
print(b.issubset(a))

